In [59]:
#importation des librairie
import pandas as pd
import numpy as np

In [60]:
#lecture du fichier et selection des colonnes qui nous interresses
df = pd.read_table("marathon.txt", names=["ville","annee","temps","secondes","estPARIS","estBERLIN"])
df

ville  annee     temps  secondes  estPARIS  estBERLIN
0      PARIS   2011  02:06:29      7589       NaN        NaN
1      PARIS   2010  02:06:41      7601       NaN        NaN
2      PARIS   2009  02:05:47      7547       NaN        NaN
3      PARIS   2008  02:06:40      7600       NaN        NaN
4      PARIS   2007  02:07:17      7637       NaN        NaN
..       ...    ...       ...       ...       ...        ...
354  CHICAGO   2006  02:07:35      7655       NaN        NaN
355  CHICAGO   2007  02:11:11      7871       NaN        NaN
356  CHICAGO   2008  02:06:25      7585       NaN        NaN
357  CHICAGO   2009  02:05:41      7541       NaN        NaN
358  CHICAGO   2010  02:06:23      7583       NaN        NaN

[359 rows x 6 columns]

In [61]:
#permet de changer le Nan en 1 pour paris et berlin 

for i in range (len(df.ville)):
    if df.ville[i] == "PARIS":
        df.estPARIS[i] = 1
        df.estBERLIN[i] = 0
        #print(sum(df.estPARIS))

    elif df.ville[i] == "BERLIN":
        df.estPARIS[i] = 0
        df.estBERLIN[i] = 1
        #print(sum(df.estBERLIN))

    else:
        df.estPARIS[i] = 0
        df.estBERLIN[i] = 0
        
print(df.head (n=3))

C:\Users\utilisateur\AppData\Local\Temp\ipykernel_14912\620780375.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.estPARIS[i] = 1
C:\Users\utilisateur\AppData\Local\Temp\ipykernel_14912\620780375.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.estBERLIN[i] = 0
C:\Users\utilisateur\AppData\Local\Temp\ipykernel_14912\620780375.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.estPARIS[i] = 0
C:\Users\utilisateur\AppDa

   ville  annee     temps  secondes  estPARIS  estBERLIN
0  PARIS   2011  02:06:29      7589       1.0        0.0
1  PARIS   2010  02:06:41      7601       1.0        0.0
2  PARIS   2009  02:05:47      7547       1.0        0.0


In [62]:
#x_transpose = 3 lignes
x_transpose= np.matrix([df.annee, df.estPARIS,df.estBERLIN])
x_transpose

matrix([[2.011e+03, 2.010e+03, 2.009e+03, ..., 2.008e+03, 2.009e+03,
         2.010e+03],
        [1.000e+00, 1.000e+00, 1.000e+00, ..., 0.000e+00, 0.000e+00,
         0.000e+00],
        [0.000e+00, 0.000e+00, 0.000e+00, ..., 0.000e+00, 0.000e+00,
         0.000e+00]])

In [63]:
#T PERMET DE FAIRE LA TRANSPOSE (x = 3 colonnes)
x = x_transpose.T
x

matrix([[2.011e+03, 1.000e+00, 0.000e+00],
        [2.010e+03, 1.000e+00, 0.000e+00],
        [2.009e+03, 1.000e+00, 0.000e+00],
        ...,
        [2.008e+03, 0.000e+00, 0.000e+00],
        [2.009e+03, 0.000e+00, 0.000e+00],
        [2.010e+03, 0.000e+00, 0.000e+00]])

In [64]:
# multiplication entre x et sa transposer
a = x_transpose*x
a

matrix([[1.42139614e+09, 6.97750000e+04, 7.57150000e+04],
        [6.97750000e+04, 3.50000000e+01, 0.00000000e+00],
        [7.57150000e+04, 0.00000000e+00, 3.80000000e+01]])

In [65]:
# inverse
a1 = np.linalg.inv(a)#commande numpy qui permet de fait l'inverse
a1

matrix([[ 8.83835274e-10, -1.76198875e-06, -1.76104178e-06],
        [-1.76198875e-06,  3.20840790e-02,  3.51076259e-03],
        [-1.76104178e-06,  3.51076259e-03,  2.98246652e-02]])

In [66]:
# inverse * transposer
a2 = a1*x_transpose
a2

matrix([[ 1.54039862e-08,  1.45201509e-08,  1.36363157e-08, ...,
          1.77474123e-06,  1.77562507e-06,  1.77650890e-06],
        [ 2.85407196e-02,  2.85424816e-02,  2.85442436e-02, ...,
         -3.53807341e-03, -3.53983540e-03, -3.54159739e-03],
        [-3.06924425e-05, -2.89314007e-05, -2.71703590e-05, ...,
         -3.53617190e-03, -3.53793294e-03, -3.53969399e-03]])

In [67]:
#initialisation de y
y =np.matrix([df.secondes]).T
y

matrix([[ 7589],
        [ 7601],
        [ 7547],
        [ 7600],
        [ 7637],
        [ 7683],
        [ 7682],
        [ 7736],
        [ 7593],
        [ 7698],
        [ 7780],
        [ 7729],
        [ 7690],
        [ 7777],
        [ 7814],
        [ 7938],
        [ 7806],
        [ 7856],
        [ 7846],
        [ 7803],
        [ 7990],
        [ 7983],
        [ 8033],
        [ 7869],
        [ 7964],
        [ 7849],
        [ 7918],
        [ 7958],
        [ 8047],
        [ 7904],
        [ 8750],
        [ 8333],
        [ 9295],
        [ 9041],
        [ 8457],
        [ 7418],
        [ 7508],
        [ 7568],
        [ 7439],
        [ 7466],
        [ 7556],
        [ 7661],
        [ 7604],
        [ 7495],
        [ 7607],
        [ 7727],
        [ 7662],
        [ 7604],
        [ 7565],
        [ 7661],
        [ 7755],
        [ 7622],
        [ 7711],
        [ 7857],
        [ 7687],
        [ 7857],
        [ 7696],
        [ 7811],
        [ 7905

In [70]:
#inverse * y
a3 =a2 * y
a3
#ou cette methode
#((x.T)*x).I*x.T*
print ('on trouve que a0 vaut',a3[0],"que a1 vaut",a3[1],"que a2 vaut",a3[2])

on trouve que a0 vaut [[3.98807104]] que a1 vaut [[-13.47591572]] que a2 vaut [[-23.91576442]]
